### ISSUE TITLE
 AWS CodeBuild migrating build hosts to AL2023

### ISSUE THREAD

**Issue by Reef1991** [aws-samples/aws-waf-ops-dashboards#11]
I have recieved the following notice from AWS, I am wondering if anything will break on my WAF Dashboard because of this change, it looks to me like Amazon linux 2 is specified for the codebuild role in the cloudformation template although it looks like this step is only for the initial Cloudformation Deployment/build of the WAF and its associated resources.

I can see Codebuild then runs once a month to deploy updates to the the waf log enrichment lambda role.

"Hello,

Starting on September 4, 2024, AWS CodeBuild will upgrade its fleet of build hosts to use Amazon Linux 2023 (AL2023) from Amazon Linux 2 (AL2) [1]. If your builds rely on AL2 as the underlying operating system, you will need to update your buildspec and any custom images to work with the AL2023. However, if you have already upgraded your buildspec or any custom images you can disregard the rest of this message.

CodeBuild provides managed container images for AL2023 and contain many of the popular runtimes [2]"

Just wondering if this will cause any issues and if so what steps can be taken against them, thanks.

**Comment by pablopagani** [comment]
Hi @Reef1991 
Thanks for reaching out. I have updated codebuild image to 
aws/codebuild/amazonlinux2-x86_64-standard:5.0
Tested and working without issues. Let me know if you see any issue.
