### ISSUE TITLE
Error Executing CodeBuild / Running LogEnrichment Lambda Function

### ISSUE THREAD

**Issue by AntonioAEMartins** [aws-samples/aws-waf-ops-dashboards#12]
@pablopagani @dgarcat @chmariot @ruvimrd 

Hello everyone, hope you're all doing well.

I'm currently working on my Capstone project in the area of MultiCloud Cybersecurity, and I'm trying to implement the AWS WAF Operations Dashboards library within our company's environment. However, I've encountered several issues that appear to stem from missing dependencies in the `.yaml` configuration file. 

The initial error I faced when running the `log_enrichment` Lambda function was:

```plaintext
[ERROR] Runtime.ImportModuleError: Unable to import module 'index': No module named 'packaging' Traceback (most recent call last):
```

I addressed this by adding the `packaging` dependency to the `.yaml` Lambda Layers. Now, however, I'm encountering a new error:

```plaintext
[ERROR] Runtime.ImportModuleError: Unable to import module 'index': No module named 'jaraco' Traceback (most recent call last):
```

If anyone has experience dealing with these dependency issues in Lambda or has suggestions on how to ensure all necessary packages are correctly included, I'd really appreciate the help. Thanks in advance!

**Comment by robertoj921** [comment]
On the CodeBuild Project resource, I added the below packages and was able to get it working again:
```
- $VIRTUAL_ENV/bin/pip3 install -U packaging
- $VIRTUAL_ENV/bin/pip3 install -U jaraco.text
- $VIRTUAL_ENV/bin/pip3 install -U platformdirs
```

**Comment by pablopagani** [comment]
Thanks @AntonioAEMartins  and @robertoj921  for submiting this issue. It should be resolved now. Can you please test and provide feedback if it'w orking for you now?
