### ISSUE TITLE
ESConfiguration Custom Resource Issue

### ISSUE THREAD

**Issue by brunokktro** [aws-samples/aws-waf-ops-dashboards#8]
![CloudFormation - Stack waf-dashboard — Mozilla Firefox](https://github.com/aws-samples/aws-waf-ops-dashboards/assets/37803210/7e1713e8-5fcf-4c5f-ab90-28e7e974b242)

Creation of stack failing and Rollback initiated because the following issue: 

"CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [a910c57e-19a1-421f-9f6a-fa922b54181e]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version."

**Comment by brunokktro** [comment]
Researching about the issue, I've found these re:Post Knowledge Article and Hashicorp website that can help, maybe...

- [How do I update the AWS CloudFormation cfn-response module for AWS Lambda functions running on Python 2.7/3.6/3.7?](https://repost.aws/knowledge-center/cloudformation-cfn-response-lambda)
-  [Requests Module Deprecation Notice for AWS Lambda in the AWS Python SDK](https://support.hashicorp.com/hc/en-us/articles/1500006776181-Requests-Module-Deprecation-Notice-for-AWS-Lambda-in-the-AWS-Python-SDK)

**Comment by pablopagani** [comment]
Hi Bruno, thanks for reporting the issue.
Those pointers are to improve response from Lambda failures to cloudFormation, but don't address the issue on Lambda function that was failing.
Either way I did a quick fix in the failing lambda function by specifying a version for the requests module.
Can you please try to deploy it again and let me know if it works for you?
Thanks!
Pablo

**Comment by pablopagani** [comment]
Issue resolved with requests version definition
