### ISSUE TITLE
ESConfiguration - 	 CREATE_FAILED

### ISSUE THREAD

**Issue by rodrigmc2024** [aws-samples/aws-waf-ops-dashboards#9]
CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [14855573-d52a-4c49-86c0-253981190145]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.

**Comment by rodrigmc2024** [comment]
This error in the lambda execution:
[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': No module named 'requests_aws4auth'

**Comment by pablopagani** [comment]
Thanks for submiting, can you test with updated runtime? Thanks!
